[project]
name = "django-medv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Maxim Ryzhov", email = "maximryzhov88@yandex.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
]

[project.scripts]
django-medv = "django_medv:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
